# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "alexsmobs:snow_leopard",
    "alexsmobs:seal",
    "infectious:zombie_batman",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "minecraft:trader_llama",
    "apocalypsenow:soldiers_02",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "undead_revamp2:thepregnant",
    "infectious:zombie_painter",
    "minecraft:llama",
    "alexsmobs:maned_wolf",
    "extinction:infected_police",
    "zombie_extreme:goon",
    "alexsmobs:skreecher",
    "infectious:glitched_zombie",
    "minecraft:tadpole",
    "infectious:nuke_explosion",
    "minecraft:dolphin",
    "zombie_extreme:devestated",
    "apocalypsenow:rat",
    "infectious:bike",
    "alexsmobs:gelada_monkey",
    "apocalypsenow:hunter",
    "enemis:boomer",
    "zombie_extreme:infected_military",
    "alexsmobs:hammerhead_shark",
    "alexsmobs:dropbear",
    "infectious:maggot_zombie",
    "infectious:deep_sea_diver_zombie",
    "alexsmobs:tiger",
    "zoniex:disemboweler",
    "infectious:zombified_spider",
    "alexsmobs:grizzly_bear",
    "infectious:construction_worker_zombie",
    "alexsmobs:murmur_head",
    "undead_revamp2:slaveman",
    "extinction:runner",
    "zombie_extreme:divided",
    "infectious:zombified_bird_flying",
    "undead_revamp2:invisiclogger",
    "undead_revamp2:invisiimmortal",
    "infectious:balloon_zombie",
    "minecraft:bee",
    "mutantsbuff:invul",
    "alexsmobs:devils_hole_pupfish",
    "infectious:zombified_bear",
    "minecraft:illusioner",
    "undead_revamp2:thebeartamer",
    "zombiesmore:explosive_zombie",
    "infectious:iron_door_zombie",
    "minecraft:mooshroom",
    "infectious:zombie_spiter",
    "takesapillage:skirmisher",
    "alexsmobs:bison",
    "infectious:swat_zombie",
    "zoniex:tormented_zombie",
    "minecraft:drowned",
    "infectious:zombie_clown",
    "minecraft:axolotl",
    "zombie_extreme:faceless",
    "prehistoricexploration:damage_box",
    "infectious:psycho_zombie",
    "zombie_extreme:revived",
    "alexsmobs:gorilla",
    "alexsmobs:tusklin",
    "zoniex:block_test",
    "undead_revamp2:thedungeon",
    "infectious:pool_tube_zombie",
    "infectious:zombie_agent",
    "alexsmobs:cosmic_cod",
    "apocalypsenow:horde_2",
    "apocalypsenow:horde_3",
    "apocalypsenow:horde_4",
    "zombie_extreme:boomer",
    "alexsmobs:underminer",
    "apocalypsenow:horde_5",
    "undead_revamp2:thespectre",
    "apocalypsenow:horde_1",
    "extinction:soldier_clicker",
    "minecraft:wandering_trader",
    "zombiesmore:boomer_zombie",
    "extinction:patient_zero",
    "alexsmobs:kangaroo",
    "zombiesmore:cursed_head",
    "undead_revamp2:propball_1",
    "extinction:patient_zero_i",
    "infectious:zombie_screamer",
    "infectious:zombie_miner",
    "alexsmobs:hummingbird",
    "mutantmonsters:mutant_zombie",
    "undead_revamp2:therod",
    "extinction:infected_hazmat",
    "hordes:drowned_player",
    "zombiesmore:tank_zombie",
    "mutantsbuff:shockwave",
    "infectious:zombified_chicken",
    "undead_revamp2:theordure",
    "undead_revamp2:theheavy",
    "alexsmobs:crow",
    "apocalypsenow:soldiers",
    "alexsmobs:guster",
    "enemis:wardi",
    "minecraft:pufferfish",
    "infectious:zombie_doctor",
    "infectious:franklin_zombie",
    "minecraft:fox",
    "immersiveengineering:bulwark",
    "undead_revamp2:clogger",
    "alexsmobs:warped_toad",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "immersiveengineering:fusilier",
    "alexsmobs:emu",
    "alexsmobs:cockroach",
    "undead_revamp2:coppertar",
    "infectious:tower_zombie",
    "apocalypsenow:looter_3",
    "infectious:zombie_bomber",
    "extinction:mercenary",
    "apocalypsenow:looter_4",
    "apocalypsenow:looter_5",
    "infectious:zombie_warrior",
    "alexsmobs:flutter",
    "apocalypsenow:looter_1",
    "minecraft:hoglin",
    "apocalypsenow:looter_2",
    "infectious:zombie_horde",
    "alexsmobs:capuchin_monkey",
    "infectious:zombie_on_stelts",
    "hordes:husk_player",
    "apocalypsenow:walker_3",
    "minecraft:polar_bear",
    "apocalypsenow:walker_2",
    "apocalypsenow:walker_5",
    "apocalypsenow:walker_4",
    "minecraft:zombified_piglin",
    "apocalypsenow:walker_1",
    "minecraft:turtle",
    "apocalypsenow:walker_7",
    "minecraft:sheep",
    "infectious:crawling_zombie",
    "infectious:zombie_fisherman",
    "apocalypsenow:walker_6",
    "apocalypsenow:walker_9",
    "apocalypsenow:walker_8",
    "infectious:zombie_miner_spawn",
    "alexsmobs:rattlesnake",
    "infectious:screamer",
    "zombie_extreme:assasin_black_ops",
    "alexsmobs:bone_serpent_part",
    "extinction:goon",
    "alexsmobs:raccoon",
    "zoniex:blood_eagle",
    "minecraft:ravager",
    "infectious:spore_zombie",
    "infectious:zombified_rex",
    "alexsmobs:bone_serpent",
    "zombie_extreme:runner",
    "infectious:headless_zombie",
    "alexsmobs:potoo",
    "alexsmobs:fly",
    "infectious:zombie_horseman_no_horse",
    "alexsmobs:straddler",
    "infectious:big_zombie",
    "alexsmobs:sea_bear",
    "extinction:boomer",
    "undead_revamp2:thewolf",
    "alexsmobs:mudskipper",
    "alexsmobs:sugar_glider",
    "infectious:mc_donalds_worker_zombie",
    "infectious:fungal_zombie",
    "undead_revamp2:thebidyupside",
    "mutantszombies:zombie_brute",
    "alexsmobs:crimson_mosquito",
    "infectious:mummy",
    "undead_revamp2:thebidy",
    "infectious:zombified_wolf",
    "alexsmobs:orca",
    "undead_revamp2:the_moonflower",
    "infectious:doom_zombie",
    "extinction:infected_mutated",
    "infectious:infectious_zombie",
    "zoniex:brutaliser",
    "infectious:door_zombie",
    "infectious:firework_zombie",
    "alexsmobs:jerboa",
    "minecraft:bat",
    "infectious:lootdrop",
    "alexsmobs:cosmaw",
    "alexsmobs:comb_jelly",
    "infectious:mecha_zombie",
    "apocalypsenow:runner_39",
    "apocalypsenow:runner_38",
    "apocalypsenow:runner_37",
    "apocalypsenow:runner_36",
    "apocalypsenow:runner_35",
    "brewery:beer_elemental",
    "apocalypsenow:runner_34",
    "apocalypsenow:crawler_3",
    "apocalypsenow:survivor_10",
    "apocalypsenow:crawler_2",
    "infectious:security_zombie",
    "undead_revamp2:thehorrors",
    "apocalypsenow:crawler_4",
    "apocalypsenow:crawler_1",
    "infectious:baseball_bat_zombie",
    "apocalypsenow:cockroach",
    "extinction:stalker_ii",
    "alexsmobs:skunk",
    "alexsmobs:enderiophage",
    "apocalypsenow:runner_49",
    "zombie_extreme:fetus",
    "apocalypsenow:runner_48",
    "alexsmobs:sunbird",
    "undead_revamp2:bigsucker",
    "apocalypsenow:runner_43",
    "apocalypsenow:runner_42",
    "apocalypsenow:runner_41",
    "alexsmobs:tasmanian_devil",
    "apocalypsenow:runner_40",
    "apocalypsenow:runner_47",
    "apocalypsenow:runner_46",
    "zombie_extreme:zero_patient",
    "apocalypsenow:runner_45",
    "chovys_apocalypse_mod:anchovy",
    "apocalypsenow:runner_44",
    "infectious:tower_zombie_1",
    "minecraft:cat",
    "alexsmobs:stradpole",
    "infectious:zombie_hitler",
    "apocalypsenow:runner_50",
    "infectious:chained_zombie",
    "infectious:bees",
    "minecraft:tropical_fish",
    "infectious:bucket_zombie",
    "zombie_extreme:chainsaw",
    "apocalypsenow:runner_54",
    "apocalypsenow:runner_53",
    "apocalypsenow:runner_52",
    "minecraft:panda",
    "minecraft:zombie_villager",
    "infectious:muscular_zombie",
    "apocalypsenow:runner_51",
    "infectious:tower_zombie_4",
    "zombie_extreme:crawler",
    "apocalypsenow:runner_57",
    "enemis:arazombie",
    "infectious:tower_zombie_3",
    "apocalypsenow:runner_56",
    "infectious:tower_zombie_2",
    "apocalypsenow:runner_55",
    "alexsmobs:froststalker",
    "zombie_extreme:demolisher",
    "minecraft:giant",
    "alexsmobs:lobster",
    "alexsmobs:seagull",
    "zombie_extreme:infected",
    "undead_revamp2:theskeeper",
    "alexsmobs:moose",
    "alexsmobs:shoebill",
    "infectious:pumpkin_zombie",
    "alexsmobs:farseer",
    "infectious:atomic_mushroom",
    "infectious:robotic_zombie",
    "alexsmobs:warped_mosco",
    "zombie_extreme:parasite",
    "immersiveengineering:commando",
    "hordes:zombie_player",
    "zombie_extreme:infected_juggernaut",
    "minecraft:husk",
    "extinction:infected_riot_gear",
    "undead_revamp2:axestrom",
    "jeffsgibbing:flesh_2",
    "prehistoricexploration:toxic",
    "alexsmobs:komodo_dragon",
    "minecraft:donkey",
    "prehistoricexploration:infected_lab",
    "prehistoricexploration:debug",
    "infectious:mutant_zombie",
    "infectious:blind_zombie",
    "infectious:beehive_zombie",
    "mutantmonsters:mutant_skeleton",
    "minecraft:piglin_brute",
    "infectious:zombie_runner",
    "extinction:traveler",
    "mutantsbuff:shockwaves",
    "zoniex:blood_eagle_tamed",
    "alexsmobs:crocodile",
    "enemis:zombie_creeper",
    "apocalypsenow:military_medic",
    "infectious:hazmat_zombie",
    "alexsmobs:triops",
    "alexsmobs:rhinoceros",
    "alexsmobs:frilled_shark",
    "infectious:giant_zombie",
    "mutantszombies:crawler",
    "alexsmobs:bald_eagle",
    "extinction:soldier",
    "undead_revamp2:neocrorines",
    "enemis:witch",
    "alexsmobs:blobfish",
    "alexsmobs:mimicube",
    "zombie_extreme:infected_police",
    "undead_revamp2:sucker",
    "alexsmobs:void_worm",
    "prehistoricexploration:incubator",
    "zombiesmore:boomer_charged",
    "enemis:kid_spider",
    "minecraft:parrot",
    "infectious:zombie_lumberjack",
    "infectious:angry_zombie",
    "zombie_extreme:inflated",
    "prehistoricexploration:toxic_split",
    "alexsmobs:centipede_head",
    "jeffsgibbing:flesh_entity",
    "minecraft:frog",
    "infectious:enchanted_zombie",
    "prehistoricexploration:impact_wave",
    "zombie_extreme:clicker",
    "alexsmobs:banana_slug",
    "enemis:lloron",
    "infectious:barrel_zombie",
    "mutantmonsters:mutant_creeper",
    "infectious:frozen_zombie",
    "infectious:armless_zombie",
    "infectious:fire_fighter_zombie",
    "alexsmobs:mimic_octopus",
    "infectious:nuke",
    "infectious:zombie_diver",
    "alexsmobs:bunfungus",
    "infectious:zombie_horseman",
    "alexsmobs:void_worm_part",
    "infectious:golden_zombie",
    "zombie_extreme:explosive_infected",
    "minecraft:mule",
    "minecraft:vindicator",
    "infectious:zombie_cook",
    "infectious:muddy_zombie",
    "alexsmobs:flying_fish",
    "mutantszombies:blister_zombie",
    "minecraft:evoker",
    "zombie_extreme:infected_hazmat",
    "undead_revamp2:thelurker",
    "alexsmobs:tarantula_hawk",
    "alexsmobs:cachalot_whale",
    "infectious:zombified_boar",
    "infectious:bodyless_zombie",
    "infectious:turret",
    "jeffs_cursed_walking_structures:driller",
    "zombie_extreme:ram",
    "infectious:ancient_zombie_boss",
    "prehistoricexploration:zombifaurus",
    "infectious:zombie_soldier",
    "infectious:zombie_prisoner",
    "infectious:sleepy_zombie",
    "undead_revamp2:thespitter",
    "jeffsgibbing:ribs",
    "takesapillage:legioner",
    "apocalypsenow:walker_29",
    "apocalypsenow:walker_28",
    "prehistoricexploration:dino_embryo",
    "apocalypsenow:walker_27",
    "apocalypsenow:walker_26",
    "apocalypsenow:walker_25",
    "infectious:burned_zombie",
    "apocalypsenow:walker_24",
    "apocalypsenow:walker_23",
    "apocalypsenow:walker_22",
    "infectious:football_player_zombie",
    "apocalypsenow:walker_21",
    "apocalypsenow:walker_20",
    "infectious:brain_zombie",
    "alexsmobs:terrapin",
    "zombiesmore:cursed_zombie",
    "alexsmobs:anaconda",
    "infectious:zombie_astronaut",
    "zoniex:skin_crawler",
    "infectious:fat_zombie",
    "undead_revamp2:thesomnolence",
    "infectious:withered_zombie",
    "infectious:pylon_zombie",
    "enemis:zombie_rated",
    "minecraft:pig",
    "enemis:kid_zombie",
    "infectious:zombie_boxer",
    "alexsmobs:alligator_snapping_turtle",
    "extinction:infected_bear",
    "infectious:beekeeper_zombie",
    "apocalypsenow:walker_33",
    "apocalypsenow:walker_32",
    "enemis:zombie_seda",
    "apocalypsenow:walker_31",
    "apocalypsenow:walker_30",
    "minecraft:goat",
    "cold_sweat:chameleon",
    "mutantmonsters:mutant_enderman",
    "minecraft:cod",
    "infectious:zombie_head",
    "undead_revamp2:theswarmer",
    "alexsmobs:mantis_shrimp",
    "infectious:zombie_archer",
    "infectious:burning_zombie",
    "infectious:zombie_scientist",
    "enemis:zombie_fire",
    "zombie_extreme:rat_king",
    "undead_revamp2:theimmortal",
    "infectious:balloon_zombie_no_balloon",
    "alexsmobs:platypus",
    "mutantmonsters:spider_pig",
    "extinction:hunter",
    "minecraft:cow",
    "alexsmobs:rocky_roller",
    "alexsmobs:soul_vulture",
    "apocalypsenow:survivor_5",
    "apocalypsenow:survivor_4",
    "apocalypsenow:survivor_3",
    "apocalypsenow:survivor_2",
    "alexsmobs:blue_jay",
    "apocalypsenow:survivor_1",
    "infectious:zombie_police",
    "alexsmobs:toucan",
    "minecraft:salmon",
    "apocalypsenow:walker_19",
    "infectious:zombified_bird",
    "apocalypsenow:walker_18",
    "apocalypsenow:walker_17",
    "undead_revamp2:bomber",
    "apocalypsenow:survivor_9",
    "apocalypsenow:walker_16",
    "apocalypsenow:survivor_8",
    "apocalypsenow:walker_15",
    "extinction:parasite",
    "undead_revamp2:smokesmitter",
    "apocalypsenow:survivor_7",
    "apocalypsenow:walker_14",
    "apocalypsenow:survivor_6",
    "apocalypsenow:walker_13",
    "apocalypsenow:walker_12",
    "apocalypsenow:walker_11",
    "alexsmobs:anteater",
    "apocalypsenow:walker_10",
    "alexsmobs:rain_frog",
    "extinction:stalker",
    "infectious:zombie_bait",
    "minecraft:rabbit",
    "minecraft:pillager",
    "infectious:zombie_breeder",
    "alexsmobs:murmur",
    "minecraft:zoglin",
    "infectious:zombie_farmer",
    "infectious:zombie_girl",
    "undead_revamp2:invisiblebidy",
    "alexsmobs:leafcutter_ant",
    "undead_revamp2:thehorrorsdecoys",
    "mutantsbuff:explosion",
    "infectious:bouncer_zombie",
    "zombie_extreme:night_hunter",
    "prehistoricexploration:zombifaurus_embryo",
    "zoniex:spine_wrencher",
    "alexsmobs:mungus",
    "alexsmobs:caiman",
    "infectious:zombie_dancer",
    "mutantsbuff:stable_explosion",
    "alexsmobs:spectre",
    "extinction:fallen_survivor",
    "alexsmobs:catfish",
    "prehistoricexploration:poison_gases",
    "mutantmonsters:endersoul_clone",
    "minecraft:piglin",
    "mutantszombies:spitter",
    "alexsmobs:skelewag",
    "undead_revamp2:thesmoker",
    "infectious:old_zombie",
    "takesapillage:archer",
    "extinction:infected_soldier",
    "undead_revamp2:flame",
    "alexsmobs:elephant",
    "undead_revamp2:thegliter",
    "apocalypsenow:military_02",
    "infectious:radioactive_zombie",
    "apocalypsenow:military_01",
    "alexsmobs:gazelle",
    "infectious:zombie",
    "minecraft:sniffer",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "infectious:acid_zombie",
    "apocalypsenow:cannibal",
    "infectious:disco_zombie",
    "zombie_extreme:military",
    "zombiesmore:crawler",
    "infectious:ancient_zombie",
    "infectious:zombie_climber",
    "zoniex:skin_crawler_summon",
    "infectious:claw_zombie",
    "minecraft:ocelot",
    "jeffsgibbing:bone_entity",
    "undead_revamp2:crackleball",
    "minecraft:wolf",
    "undead_revamp2:thehunter",
    "extinction:runner_ii",
    "undead_revamp2:deadclogger"
]
