#If true, Blister Zombies will spawn naturally | default: true
blisterZombiesSpawnNaturally = true
#If true, Crawlers will spawn naturally | default: true
crawlersSpawnNaturally = true
#If true, Spitter Zombies will spawn naturally | default: true
spitterZombiesSpawnNaturally = true
#If true, Zombie Brutes will spawn naturally | default: true
zombieBrutesSpawnNaturally = true

